avro.schema.registry.url: http://djbk02lax01us.dev.prod.auction.local:8081

kafka.bootstrap.servers: djbk02lax01us.dev.prod.auction.local:9092

spring:
    cloud:
        discovery:
            enabled: false